export function Hastebin(String: string, EmbedColor?: string): Promise<any>;
export function RandomString(Length: number, EmbedColor?: string): Promise<any>;
export function DiscordSpoiler(String: string, EmbedColor?: string): Promise<any>;
export function GetMeme(EmbedColor?: string): Promise<any>;
export function GetJoke(EmbedColor?: string): Promise<any>;
export function GetAdvice(EmbedColor?: string): Promise<any>;
export function GetFact(EmbedColor?: string): Promise<any>;
export function GetWhy(EmbedColor?: string): Promise<any>;
export function MinecraftAchievemen(String: string, EmbedColor?: string): Promise<any>;
export function Tweet(Name: string, Tweet: string, EmbedColor?: string): Promise<any>;
export function PornhubComment(Name: string, Image: string, Comment: string, EmbedColor?: string): Promise<any>;
export function Lmgtfy(String: string, EmbedColor?: string): Promise<any>;
export function GetAnimeStuff(Thing: 'neko' | 'nekogif' | 'foxgirl' | 'waifu' | 'smug' | 'baka' | 'slap' | 'poke' | 'pat' | 'hug' | 'kiss' | 'tickle', EmbedColor?: string): Promise<any>;
export function GetAnimalStuff(Thing: 'dog' | 'cat' | 'duck' | 'bird' | 'panda' | 'wolf' | 'fox' | 'seal" | "llama" | "alpaca" | "camel" | "lizard" | "snake", EmbedColor?: string): Promise<any>;
